<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;

class CategoriesSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            'INCOME' => [
                [
                    'name_en' => 'Work & Business',
                    'name_ru' => 'Работа и бизнес',
                    'slug'    => 'work-business',
                    'children' => [
                        ['name_en' => 'Salary', 'name_ru' => 'Зарплата', 'slug' => 'salary'],
                        ['name_en' => 'Freelance', 'name_ru' => 'Фриланс', 'slug' => 'freelance'],
                        ['name_en' => 'Side Jobs', 'name_ru' => 'Подработки', 'slug' => 'side-jobs'],
                        ['name_en' => 'Business Profit', 'name_ru' => 'Прибыль от бизнеса', 'slug' => 'business-profit'],
                        ['name_en' => 'Selling Services', 'name_ru' => 'Продажа услуг', 'slug' => 'selling-services'],
                        ['name_en' => 'Consulting', 'name_ru' => 'Консалтинг', 'slug' => 'consulting'],
                        ['name_en' => 'Online Coaching', 'name_ru' => 'Онлайн-коучинг', 'slug' => 'online-coaching'],
                    ],
                ],
                [
                    'name_en' => 'Investments & Capital',
                    'name_ru' => 'Инвестиции и капитал',
                    'slug'    => 'investments-capital',
                    'children' => [
                        ['name_en' => 'Investments', 'name_ru' => 'Инвестиции', 'slug' => 'investments'],
                        ['name_en' => 'Dividends', 'name_ru' => 'Дивиденды', 'slug' => 'dividends'],
                        ['name_en' => 'Currency Exchange Profit', 'name_ru' => 'Доход от валюты', 'slug' => 'currency-profit'],
                        ['name_en' => 'Digital Assets Sale', 'name_ru' => 'Продажа цифровых активов', 'slug' => 'digital-assets-sale'],
                        ['name_en' => 'Royalties', 'name_ru' => 'Роялти', 'slug' => 'royalties'],
                        ['name_en' => 'Intellectual Property Sale', 'name_ru' => 'Продажа интеллектуальной собственности', 'slug' => 'ip-sale'],
                        ['name_en' => 'Crypto Staking Rewards', 'name_ru' => 'Награды за стейкинг крипты', 'slug' => 'crypto-staking'],
                        ['name_en' => 'NFT Sales', 'name_ru' => 'Продажа NFT', 'slug' => 'nft-sales'],
                        ['name_en' => 'DeFi Yield Farming', 'name_ru' => 'DeFi фарминг', 'slug' => 'defi-yield'],
                    ],
                ],
                [
                    'name_en' => 'Real Estate & Rent',
                    'name_ru' => 'Недвижимость и аренда',
                    'slug'    => 'real-estate-rent',
                    'children' => [
                        ['name_en' => 'Rent', 'name_ru' => 'Аренда', 'slug' => 'rent'],
                        ['name_en' => 'Rental Equipment/Transport', 'name_ru' => 'Аренда техники/транспорта', 'slug' => 'rental-equipment'],
                        ['name_en' => 'Property Sale', 'name_ru' => 'Продажа недвижимости', 'slug' => 'property-sale'],
                        ['name_en' => 'Co-working Spaces', 'name_ru' => 'Аренда коворкингов', 'slug' => 'coworking-spaces'],
                    ],
                ],
                [
                    'name_en' => 'Social & Personal',
                    'name_ru' => 'Социальные и личные',
                    'slug'    => 'social-personal',
                    'children' => [
                        ['name_en' => 'Social Payments', 'name_ru' => 'Социальные выплаты', 'slug' => 'social-payments'],
                        ['name_en' => 'Pension', 'name_ru' => 'Пенсия', 'slug' => 'pension'],
                        ['name_en' => 'Scholarship / Grant', 'name_ru' => 'Стипендия / грант', 'slug' => 'scholarship'],
                        ['name_en' => 'Gifts', 'name_ru' => 'Подарки', 'slug' => 'gifts'],
                        ['name_en' => 'Prizes', 'name_ru' => 'Призы', 'slug' => 'prizes'],
                        ['name_en' => 'Inheritance', 'name_ru' => 'Наследство', 'slug' => 'inheritance'],
                        ['name_en' => 'Alimony', 'name_ru' => 'Алименты', 'slug' => 'alimony'],
                    ],
                ],
                [
                    'name_en' => 'Refunds & Donations',
                    'name_ru' => 'Возвраты и донаты',
                    'slug'    => 'refunds-donations',
                    'children' => [
                        ['name_en' => 'Debt Return', 'name_ru' => 'Возврат долгов', 'slug' => 'debt-return'],
                        ['name_en' => 'Refunds & Compensations', 'name_ru' => 'Возвраты и компенсации', 'slug' => 'refunds'],
                        ['name_en' => 'Crowdfunding / Donations Received', 'name_ru' => 'Пожертвования / донаты', 'slug' => 'donations'],
                        ['name_en' => 'Affiliate & Advertising', 'name_ru' => 'Партнёрки и реклама', 'slug' => 'affiliate'],
                        ['name_en' => 'Online Projects', 'name_ru' => 'Онлайн-проекты', 'slug' => 'online-projects'],
                        ['name_en' => 'Cashback', 'name_ru' => 'Кэшбэк', 'slug' => 'cashback'],
                        ['name_en' => 'Referral Programs', 'name_ru' => 'Реферальные программы', 'slug' => 'referral-programs'],
                    ],
                ],
                [
                    'name_en' => 'Loans',
                    'name_ru' => 'Займы',
                    'slug'    => 'loans',
                    'children' => [
                        ['name_en' => 'Loans Received', 'name_ru' => 'Полученные займы', 'slug' => 'loans-received'],
                    ],
                ],
                [
                    'name_en' => 'Other',
                    'name_ru' => 'Прочее',
                    'slug'    => 'other',
                    'children' => [
                        ['name_en' => 'Other Income', 'name_ru' => 'Прочие доходы', 'slug' => 'other-income'],
                    ],
                ],
            ],
            'EXPENSE' => [
                [
                    'name_en' => 'Housing & Utilities',
                    'name_ru' => 'Жильё и коммуналка',
                    'slug'    => 'housing-utilities',
                    'children' => [
                        ['name_en' => 'Housing', 'name_ru' => 'Жильё', 'slug' => 'housing'],
                        ['name_en' => 'Rent / Mortgage', 'name_ru' => 'Аренда / ипотека', 'slug' => 'rent-mortgage'],
                        ['name_en' => 'Utilities', 'name_ru' => 'Коммунальные услуги', 'slug' => 'utilities'],
                        ['name_en' => 'Internet & Mobile', 'name_ru' => 'Интернет и связь', 'slug' => 'internet-mobile'],
                        ['name_en' => 'Household Goods', 'name_ru' => 'Товары для дома', 'slug' => 'household-goods'],
                        ['name_en' => 'Furniture & Appliances', 'name_ru' => 'Мебель и техника', 'slug' => 'furniture-appliances'],
                        ['name_en' => 'Home Renovation & Repairs', 'name_ru' => 'Ремонт и благоустройство', 'slug' => 'home-renovation'],
                        ['name_en' => 'Home Security', 'name_ru' => 'Охрана дома', 'slug' => 'home-security'],
                        ['name_en' => 'Smart Home Devices', 'name_ru' => 'Умные устройства для дома', 'slug' => 'smart-home'],
                        ['name_en' => 'Cleaning Services', 'name_ru' => 'Клининговые услуги', 'slug' => 'cleaning-services'],
                    ],
                ],
                [
                    'name_en' => 'Online Shopping & Marketplaces',
                    'name_ru' => 'Онлайн-шопинг и маркетплейсы',
                    'slug'    => 'online-shopping-marketplaces',
                    'children' => [
                        ['name_en' => 'Amazon', 'name_ru' => 'Амазон', 'slug' => 'amazon'],
                        ['name_en' => 'AliExpress', 'name_ru' => 'Алиэкспресс', 'slug' => 'aliexpress'],
                        ['name_en' => 'eBay', 'name_ru' => 'eBay', 'slug' => 'ebay'],
                        ['name_en' => 'Wildberries', 'name_ru' => 'Вайлдбериз', 'slug' => 'wildberries'],
                        ['name_en' => 'OZON', 'name_ru' => 'ОЗОН', 'slug' => 'ozon'],
                        ['name_en' => 'Yandex Market', 'name_ru' => 'Яндекс Маркет', 'slug' => 'yandex-market'],
                        ['name_en' => 'ASOS', 'name_ru' => 'ASOS', 'slug' => 'asos'],
                        ['name_en' => 'Shein', 'name_ru' => 'Шэин', 'slug' => 'shein'],
                        ['name_en' => 'Taobao', 'name_ru' => 'Таобао', 'slug' => 'taobao'],
                        ['name_en' => 'Etsy', 'name_ru' => 'Etsy', 'slug' => 'etsy'],
                        ['name_en' => 'Alibaba', 'name_ru' => 'Алибаба', 'slug' => 'alibaba'],
                        ['name_en' => 'JD.com', 'name_ru' => 'JD.com', 'slug' => 'jd-com'],
                        ['name_en' => 'Mercado Libre', 'name_ru' => 'Меркадо Либре', 'slug' => 'mercado-libre'],
                        ['name_en' => 'Shopee', 'name_ru' => 'Шопи', 'slug' => 'shopee'],
                        ['name_en' => 'Lazada', 'name_ru' => 'Лазада', 'slug' => 'lazada'],
                        ['name_en' => 'Noon', 'name_ru' => 'Нун', 'slug' => 'noon'],
                        ['name_en' => 'Flipkart', 'name_ru' => 'Флипкарт', 'slug' => 'flipkart'],
                        ['name_en' => 'Walmart Online', 'name_ru' => 'Волмарт онлайн', 'slug' => 'walmart-online'],
                        ['name_en' => 'Target Online', 'name_ru' => 'Таргет онлайн', 'slug' => 'target-online'],
                        ['name_en' => 'Best Buy Online', 'name_ru' => 'Бест Бай онлайн', 'slug' => 'bestbuy-online'],
                        ['name_en' => 'Newegg', 'name_ru' => 'Ньюегг', 'slug' => 'newegg'],
                        ['name_en' => 'Steam', 'name_ru' => 'Стим', 'slug' => 'steam'],
                        ['name_en' => 'Epic Games Store', 'name_ru' => 'Эпик Геймс Стор', 'slug' => 'epic-games'],
                        ['name_en' => 'App Store', 'name_ru' => 'Эп Стор', 'slug' => 'app-store'],
                        ['name_en' => 'Google Play', 'name_ru' => 'Гугл Плей', 'slug' => 'google-play'],
                        ['name_en' => 'Microsoft Store', 'name_ru' => 'Майкрософт Стор', 'slug' => 'microsoft-store'],
                        ['name_en' => 'Nintendo eShop', 'name_ru' => 'Нинтендо иШоп', 'slug' => 'nintendo-eshop'],
                        ['name_en' => 'PlayStation Store', 'name_ru' => 'Плейстейшн Стор', 'slug' => 'playstation-store'],
                        ['name_en' => 'Xbox Store', 'name_ru' => 'Иксбокс Стор', 'slug' => 'xbox-store'],
                        ['name_en' => 'Other Marketplaces', 'name_ru' => 'Другие маркетплейсы', 'slug' => 'other-marketplaces'],
                    ],
                ],

                [
                    'name_en' => 'Digital Goods & Content',
                    'name_ru' => 'Цифровые товары и контент',
                    'slug'    => 'digital-goods-content',
                    'children' => [
                        ['name_en' => 'E-books', 'name_ru' => 'Электронные книги', 'slug' => 'e-books'],
                        ['name_en' => 'Audiobooks', 'name_ru' => 'Аудиокниги', 'slug' => 'audiobooks'],
                        ['name_en' => 'Online Courses', 'name_ru' => 'Онлайн-курсы', 'slug' => 'online-courses'],
                        ['name_en' => 'Digital Music', 'name_ru' => 'Цифровая музыка', 'slug' => 'digital-music'],
                        ['name_en' => 'Movies & TV Shows', 'name_ru' => 'Фильмы и сериалы', 'slug' => 'movies-tv-shows'],
                        ['name_en' => 'Software Licenses', 'name_ru' => 'Лицензии ПО', 'slug' => 'software-licenses'],
                        ['name_en' => 'Mobile Apps', 'name_ru' => 'Мобильные приложения', 'slug' => 'mobile-apps'],
                        ['name_en' => 'In-App Purchases', 'name_ru' => 'Внутриигровые покупки', 'slug' => 'in-app-purchases'],
                        ['name_en' => 'Game DLC & Add-ons', 'name_ru' => 'DLC и дополнения', 'slug' => 'game-dlc'],
                        ['name_en' => 'Digital Art', 'name_ru' => 'Цифровое искусство', 'slug' => 'digital-art'],
                        ['name_en' => 'Fonts & Graphics', 'name_ru' => 'Шрифты и графика', 'slug' => 'fonts-graphics'],
                        ['name_en' => 'Website Templates', 'name_ru' => 'Шаблоны сайтов', 'slug' => 'website-templates'],
                        ['name_en' => 'Stock Photos & Videos', 'name_ru' => 'Стоковые фото и видео', 'slug' => 'stock-media'],
                        ['name_en' => 'Digital Subscriptions', 'name_ru' => 'Цифровые подписки', 'slug' => 'digital-subscriptions'],
                    ],
                ],

                [
                    'name_en' => 'Delivery & Logistics',
                    'name_ru' => 'Доставка и логистика',
                    'slug'    => 'delivery-logistics',
                    'children' => [
                        ['name_en' => 'Delivery Services', 'name_ru' => 'Службы доставки', 'slug' => 'delivery-services'],
                        ['name_en' => 'Express Delivery', 'name_ru' => 'Экспресс-доставка', 'slug' => 'express-delivery'],
                        ['name_en' => 'International Shipping', 'name_ru' => 'Международная доставка', 'slug' => 'international-shipping'],
                        ['name_en' => 'Pickup Points', 'name_ru' => 'Пункты выдачи', 'slug' => 'pickup-points'],
                        ['name_en' => 'Customs Fees', 'name_ru' => 'Таможенные сборы', 'slug' => 'customs-fees'],
                        ['name_en' => 'Packaging', 'name_ru' => 'Упаковка', 'slug' => 'packaging'],
                        ['name_en' => 'Delivery Insurance', 'name_ru' => 'Страховка доставки', 'slug' => 'delivery-insurance'],
                        ['name_en' => 'Return Shipping', 'name_ru' => 'Доставка возвратов', 'slug' => 'return-shipping'],
                    ],
                ],

                [
                    'name_en' => 'Electronics & Gadgets',
                    'name_ru' => 'Электроника и гаджеты',
                    'slug'    => 'electronics-gadgets',
                    'children' => [
                        ['name_en' => 'Smartphones', 'name_ru' => 'Смартфоны', 'slug' => 'smartphones'],
                        ['name_en' => 'Laptops & Computers', 'name_ru' => 'Ноутбуки и компьютеры', 'slug' => 'laptops-computers'],
                        ['name_en' => 'Tablets', 'name_ru' => 'Планшеты', 'slug' => 'tablets'],
                        ['name_en' => 'Smart Watches', 'name_ru' => 'Умные часы', 'slug' => 'smart-watches'],
                        ['name_en' => 'Headphones & Audio', 'name_ru' => 'Наушники и аудио', 'slug' => 'headphones-audio'],
                        ['name_en' => 'Cameras', 'name_ru' => 'Камеры', 'slug' => 'cameras'],
                        ['name_en' => 'Gaming Consoles', 'name_ru' => 'Игровые консоли', 'slug' => 'gaming-consoles'],
                        ['name_en' => 'Smart Home Devices', 'name_ru' => 'Умные устройства для дома', 'slug' => 'smart-home-devices'],
                        ['name_en' => 'Accessories', 'name_ru' => 'Аксессуары', 'slug' => 'electronics-accessories'],
                        ['name_en' => 'Components & Parts', 'name_ru' => 'Комплектующие и запчасти', 'slug' => 'components-parts'],
                    ],
                ],

                [
                    'name_en' => 'Fashion & Apparel',
                    'name_ru' => 'Мода и одежда',
                    'slug'    => 'fashion-apparel',
                    'children' => [
                        ['name_en' => 'Clothing', 'name_ru' => 'Одежда', 'slug' => 'clothing'],
                        ['name_en' => 'Shoes', 'name_ru' => 'Обувь', 'slug' => 'shoes'],
                        ['name_en' => 'Accessories', 'name_ru' => 'Аксессуары', 'slug' => 'fashion-accessories'],
                        ['name_en' => 'Jewelry', 'name_ru' => 'Украшения', 'slug' => 'jewelry'],
                        ['name_en' => 'Watches', 'name_ru' => 'Часы', 'slug' => 'watches'],
                        ['name_en' => 'Bags & Luggage', 'name_ru' => 'Сумки и багаж', 'slug' => 'bags-luggage'],
                        ['name_en' => 'Sportswear', 'name_ru' => 'Спортивная одежда', 'slug' => 'sportswear'],
                        ['name_en' => 'Underwear & Socks', 'name_ru' => 'Нижнее белье и носки', 'slug' => 'underwear-socks'],
                    ],
                ],
                [
                    'name_en' => 'Personal & Lifestyle',
                    'name_ru' => 'Личное и образ жизни',
                    'slug'    => 'personal-lifestyle',
                    'children' => [
                        ['name_en' => 'Clothes & Accessories', 'name_ru' => 'Одежда и аксессуары', 'slug' => 'clothes-accessories'],
                        ['name_en' => 'Beauty & Care', 'name_ru' => 'Красота и уход', 'slug' => 'beauty-care'],
                        ['name_en' => 'Hairdresser & Barbershop', 'name_ru' => 'Парикмахерская и барбершоп', 'slug' => 'hairdresser-barbershop'],
                        ['name_en' => 'Cosmetics & Perfumes', 'name_ru' => 'Косметика и парфюмерия', 'slug' => 'cosmetics-perfumes'],
                        ['name_en' => 'Smartphones & Gadgets', 'name_ru' => 'Смартфоны и гаджеты', 'slug' => 'smartphones-gadgets'],
                        ['name_en' => 'Computers & Laptops', 'name_ru' => 'Компьютеры и ноутбуки', 'slug' => 'computers-laptops'],
                        ['name_en' => 'Wearable Tech', 'name_ru' => 'Носимые устройства', 'slug' => 'wearable-tech'],
                        ['name_en' => 'Hobbies & Collections', 'name_ru' => 'Хобби и коллекции', 'slug' => 'hobbies'],
                        ['name_en' => 'Photography & Video', 'name_ru' => 'Фото и видео', 'slug' => 'photography-video'],
                        ['name_en' => 'Art & Crafts', 'name_ru' => 'Искусство и рукоделие', 'slug' => 'art-crafts'],
                    ],
                ],
                [
                    'name_en' => 'Digital & Technology',
                    'name_ru' => 'Цифровые услуги и технологии',
                    'slug'    => 'digital-technology',
                    'children' => [
                        ['name_en' => 'Streaming Services', 'name_ru' => 'Стриминговые сервисы', 'slug' => 'streaming-services'],
                        ['name_en' => 'Cloud Storage', 'name_ru' => 'Облачное хранилище', 'slug' => 'cloud-storage'],
                        ['name_en' => 'Software & Apps', 'name_ru' => 'ПО и приложения', 'slug' => 'software-apps'],
                        ['name_en' => 'Online Courses & Education', 'name_ru' => 'Онлайн-курсы и обучение', 'slug' => 'online-courses'],
                        ['name_en' => 'Digital Subscriptions', 'name_ru' => 'Цифровые подписки', 'slug' => 'digital-subscriptions'],
                        ['name_en' => 'VPN Services', 'name_ru' => 'VPN сервисы', 'slug' => 'vpn-services'],
                        ['name_en' => 'Domain & Hosting', 'name_ru' => 'Домены и хостинг', 'slug' => 'domain-hosting'],
                        ['name_en' => 'AI Tools & Services', 'name_ru' => 'AI инструменты и сервисы', 'slug' => 'ai-tools'],
                        ['name_en' => 'Digital Assets Purchase', 'name_ru' => 'Покупка цифровых активов', 'slug' => 'digital-assets-purchase'],
                    ],
                ],
                [
                    'name_en' => 'Family & Children',
                    'name_ru' => 'Семья и дети',
                    'slug'    => 'family-children',
                    'children' => [
                        ['name_en' => 'Children & Education', 'name_ru' => 'Дети и образование', 'slug' => 'children-education'],
                        ['name_en' => 'Tutors', 'name_ru' => 'Репетиторы', 'slug' => 'tutors'],
                        ['name_en' => 'Courses & Extracurricular', 'name_ru' => 'Курсы и дополнительные занятия', 'slug' => 'courses-extracurricular'],
                        ['name_en' => 'Gifts to Others', 'name_ru' => 'Подарки другим', 'slug' => 'gifts-others'],
                        ['name_en' => 'Pets & Veterinary', 'name_ru' => 'Животные и ветеринария', 'slug' => 'pets-veterinary'],
                        ['name_en' => 'Baby Products', 'name_ru' => 'Детские товары', 'slug' => 'baby-products'],
                        ['name_en' => 'Childcare', 'name_ru' => 'Уход за детьми', 'slug' => 'childcare'],
                        ['name_en' => 'Family Activities', 'name_ru' => 'Семейные мероприятия', 'slug' => 'family-activities'],
                    ],
                ],
                [
                    'name_en' => 'Food & Dining',
                    'name_ru' => 'Еда и питание',
                    'slug'    => 'food-dining',
                    'children' => [
                        ['name_en' => 'Groceries', 'name_ru' => 'Продукты', 'slug' => 'groceries'],
                        ['name_en' => 'Restaurants & Cafes', 'name_ru' => 'Рестораны и кафе', 'slug' => 'restaurants-cafes'],
                        ['name_en' => 'Coffee & Snacks', 'name_ru' => 'Кофе и перекусы', 'slug' => 'coffee-snacks'],
                        ['name_en' => 'Food Delivery', 'name_ru' => 'Доставка еды', 'slug' => 'food-delivery'],
                        ['name_en' => 'Meal Kits', 'name_ru' => 'Наборы еды', 'slug' => 'meal-kits'],
                        ['name_en' => 'Healthy Food', 'name_ru' => 'Здоровая еда', 'slug' => 'healthy-food'],
                        ['name_en' => 'Alcohol', 'name_ru' => 'Алкоголь', 'slug' => 'alcohol'],
                        ['name_en' => 'Water Delivery', 'name_ru' => 'Доставка воды', 'slug' => 'water-delivery'],
                    ],
                ],
                [
                    'name_en' => 'Entertainment & Leisure',
                    'name_ru' => 'Развлечения и досуг',
                    'slug'    => 'entertainment-leisure',
                    'children' => [
                        ['name_en' => 'Bars & Clubs', 'name_ru' => 'Бары и клубы', 'slug' => 'bars-clubs'],
                        ['name_en' => 'Cinema & Theatre', 'name_ru' => 'Кино и театр', 'slug' => 'cinema-theatre'],
                        ['name_en' => 'Music & Concerts', 'name_ru' => 'Музыка и концерты', 'slug' => 'music-concerts'],
                        ['name_en' => 'Games & Gaming', 'name_ru' => 'Игры и гейминг', 'slug' => 'games-gaming'],
                        ['name_en' => 'Books & Magazines', 'name_ru' => 'Книги и журналы', 'slug' => 'books-magazines'],
                        ['name_en' => 'Museums & Exhibitions', 'name_ru' => 'Музеи и выставки', 'slug' => 'museums-exhibitions'],
                        ['name_en' => 'Events & Festivals', 'name_ru' => 'Мероприятия и фестивали', 'slug' => 'events-festivals'],
                        ['name_en' => 'Sports Events', 'name_ru' => 'Спортивные события', 'slug' => 'sports-events'],
                        ['name_en' => 'Escape Rooms & Quests', 'name_ru' => 'Квесты и эскейп-румы', 'slug' => 'escape-rooms'],
                    ],
                ],
                [
                    'name_en' => 'Travel & Tourism',
                    'name_ru' => 'Путешествия и туризм',
                    'slug'    => 'travel-tourism',
                    'children' => [
                        ['name_en' => 'Travel Tickets', 'name_ru' => 'Билеты на поездки', 'slug' => 'travel-tickets'],
                        ['name_en' => 'Accommodation', 'name_ru' => 'Проживание', 'slug' => 'accommodation'],
                        ['name_en' => 'Tours & Excursions', 'name_ru' => 'Туры и экскурсии', 'slug' => 'tours-excursions'],
                        ['name_en' => 'Travel Insurance', 'name_ru' => 'Туристическая страховка', 'slug' => 'travel-insurance'],
                        ['name_en' => 'Souvenirs', 'name_ru' => 'Сувениры', 'slug' => 'souvenirs'],
                        ['name_en' => 'Visa & Documents', 'name_ru' => 'Виза и документы', 'slug' => 'visa-documents'],
                        ['name_en' => 'Airport Services', 'name_ru' => 'Аэропортовые услуги', 'slug' => 'airport-services'],
                        ['name_en' => 'Car Rental', 'name_ru' => 'Аренда авто', 'slug' => 'car-rental'],
                    ],
                ],
                [
                    'name_en' => 'Transport & Mobility',
                    'name_ru' => 'Транспорт и мобильность',
                    'slug'    => 'transport-mobility',
                    'children' => [
                        ['name_en' => 'Public Transport', 'name_ru' => 'Общественный транспорт', 'slug' => 'public-transport'],
                        ['name_en' => 'Taxi & Ride-sharing', 'name_ru' => 'Такси и каршеринг', 'slug' => 'taxi-ride-sharing'],
                        ['name_en' => 'Fuel', 'name_ru' => 'Топливо', 'slug' => 'fuel'],
                        ['name_en' => 'Car Maintenance', 'name_ru' => 'Обслуживание авто', 'slug' => 'car-maintenance'],
                        ['name_en' => 'Parking & Tolls', 'name_ru' => 'Парковка и платные дороги', 'slug' => 'parking-tolls'],
                        ['name_en' => 'Car Insurance', 'name_ru' => 'Страховка авто', 'slug' => 'car-insurance'],
                        ['name_en' => 'Bike & Scooter Sharing', 'name_ru' => 'Прокат велосипедов и самокатов', 'slug' => 'bike-scooter-sharing'],
                        ['name_en' => 'EV Charging', 'name_ru' => 'Зарядка электромобиля', 'slug' => 'ev-charging'],
                    ],
                ],
                [
                    'name_en' => 'Health & Wellness',
                    'name_ru' => 'Здоровье и wellness',
                    'slug'    => 'health-wellness',
                    'children' => [
                        ['name_en' => 'Doctors & Specialists', 'name_ru' => 'Врачи и специалисты', 'slug' => 'doctors-specialists'],
                        ['name_en' => 'Dentist', 'name_ru' => 'Стоматолог', 'slug' => 'dentist'],
                        ['name_en' => 'Medicine & Pharmacy', 'name_ru' => 'Медицина и аптека', 'slug' => 'medicine-pharmacy'],
                        ['name_en' => 'Fitness & Gym', 'name_ru' => 'Фитнес и тренажерный зал', 'slug' => 'fitness-gym'],
                        ['name_en' => 'Yoga & Meditation', 'name_ru' => 'Йога и медитация', 'slug' => 'yoga-meditation'],
                        ['name_en' => 'Health Insurance', 'name_ru' => 'Медицинская страховка', 'slug' => 'health-insurance'],
                        ['name_en' => 'Wellness & Spa', 'name_ru' => 'Wellness и спа', 'slug' => 'wellness-spa'],
                        ['name_en' => 'Mental Health', 'name_ru' => 'Психическое здоровье', 'slug' => 'mental-health'],
                        ['name_en' => 'Sports Nutrition', 'name_ru' => 'Спортивное питание', 'slug' => 'sports-nutrition'],
                        ['name_en' => 'Medical Devices', 'name_ru' => 'Медицинские устройства', 'slug' => 'medical-devices'],
                    ],
                ],
                [
                    'name_en' => 'Finance & Investments',
                    'name_ru' => 'Финансы и инвестиции',
                    'slug'    => 'finance-investments',
                    'children' => [
                        ['name_en' => 'Credits & Debts', 'name_ru' => 'Кредиты и долги', 'slug' => 'credits-debts'],
                        ['name_en' => 'Transfers', 'name_ru' => 'Переводы', 'slug' => 'transfers'],
                        ['name_en' => 'Investments Purchase', 'name_ru' => 'Покупка инвестиций', 'slug' => 'investments-purchase'],
                        ['name_en' => 'Insurance', 'name_ru' => 'Страхование', 'slug' => 'insurance'],
                        ['name_en' => 'Currency Exchange', 'name_ru' => 'Обмен валюты', 'slug' => 'currency-exchange'],
                        ['name_en' => 'Loans Given', 'name_ru' => 'Выданные займы', 'slug' => 'loans-given'],
                        ['name_en' => 'Taxes', 'name_ru' => 'Налоги', 'slug' => 'taxes'],
                        ['name_en' => 'Bank Fees & Commissions', 'name_ru' => 'Банковские комиссии', 'slug' => 'bank-fees'],
                        ['name_en' => 'Crypto Purchases', 'name_ru' => 'Покупка криптовалюты', 'slug' => 'crypto-purchases'],
                        ['name_en' => 'NFT Purchases', 'name_ru' => 'Покупка NFT', 'slug' => 'nft-purchases'],
                        ['name_en' => 'Retirement Contributions', 'name_ru' => 'Пенсионные взносы', 'slug' => 'retirement-contributions'],
                    ],
                ],
                [
                    'name_en' => 'Business & Career',
                    'name_ru' => 'Бизнес и карьера',
                    'slug'    => 'business-career',
                    'children' => [
                        ['name_en' => 'Business Expenses', 'name_ru' => 'Бизнес-расходы', 'slug' => 'business-expenses'],
                        ['name_en' => 'Office Supplies', 'name_ru' => 'Канцелярия', 'slug' => 'office-supplies'],
                        ['name_en' => 'Professional Development', 'name_ru' => 'Профессиональное развитие', 'slug' => 'professional-development'],
                        ['name_en' => 'Conferences & Seminars', 'name_ru' => 'Конференции и семинары', 'slug' => 'conferences-seminars'],
                        ['name_en' => 'Business Travel', 'name_ru' => 'Командировки', 'slug' => 'business-travel'],
                        ['name_en' => 'Marketing & Advertising', 'name_ru' => 'Маркетинг и реклама', 'slug' => 'marketing-advertising'],
                        ['name_en' => 'Legal Services', 'name_ru' => 'Юридические услуги', 'slug' => 'legal-services'],
                        ['name_en' => 'Accounting Services', 'name_ru' => 'Бухгалтерские услуги', 'slug' => 'accounting-services'],
                        ['name_en' => 'Co-working Membership', 'name_ru' => 'Членство в коворкинге', 'slug' => 'coworking-membership'],
                    ],
                ],
                [
                    'name_en' => 'Social & Charity',
                    'name_ru' => 'Социальное и благотворительность',
                    'slug'    => 'social-charity',
                    'children' => [
                        ['name_en' => 'Charity & Donations', 'name_ru' => 'Благотворительность', 'slug' => 'charity'],
                        ['name_en' => 'Gifts to Friends', 'name_ru' => 'Подарки друзьям', 'slug' => 'gifts-friends'],
                        ['name_en' => 'Weddings & Celebrations', 'name_ru' => 'Свадьбы и праздники', 'slug' => 'weddings-celebrations'],
                        ['name_en' => 'Crowdfunding Support', 'name_ru' => 'Поддержка краудфандинга', 'slug' => 'crowdfunding-support'],
                        ['name_en' => 'Community Events', 'name_ru' => 'Мероприятия сообщества', 'slug' => 'community-events'],
                        ['name_en' => 'Religious Donations', 'name_ru' => 'Религиозные пожертвования', 'slug' => 'religious-donations'],
                    ],
                ],
                [
                    'name_en' => 'Subscriptions & Services',
                    'name_ru' => 'Подписки и сервисы',
                    'slug'    => 'subscriptions-services',
                    'children' => [
                        ['name_en' => 'Streaming Entertainment', 'name_ru' => 'Стриминговые развлечения', 'slug' => 'streaming-entertainment'],
                        ['name_en' => 'Music Streaming', 'name_ru' => 'Музыкальные стриминги', 'slug' => 'music-streaming'],
                        ['name_en' => 'Gaming Subscriptions', 'name_ru' => 'Игровые подписки', 'slug' => 'gaming-subscriptions'],
                        ['name_en' => 'News & Media', 'name_ru' => 'Новости и медиа', 'slug' => 'news-media'],
                        ['name_en' => 'Productivity Tools', 'name_ru' => 'Инструменты продуктивности', 'slug' => 'productivity-tools'],
                        ['name_en' => 'Delivery Subscriptions', 'name_ru' => 'Подписки на доставку', 'slug' => 'delivery-subscriptions'],
                        ['name_en' => 'Membership Programs', 'name_ru' => 'Программы членства', 'slug' => 'membership-programs'],
                    ],
                ],
                [
                    'name_en' => 'Education & Self-development',
                    'name_ru' => 'Образование и саморазвитие',
                    'slug'    => 'education-selfdevelopment',
                    'children' => [
                        ['name_en' => 'Online Courses', 'name_ru' => 'Онлайн-курсы', 'slug' => 'online-courses'],
                        ['name_en' => 'Books & Educational Materials', 'name_ru' => 'Книги и учебные материалы', 'slug' => 'educational-materials'],
                        ['name_en' => 'Workshops & Masterclasses', 'name_ru' => 'Воркшопы и мастер-классы', 'slug' => 'workshops-masterclasses'],
                        ['name_en' => 'Certifications', 'name_ru' => 'Сертификации', 'slug' => 'certifications'],
                        ['name_en' => 'Language Learning', 'name_ru' => 'Изучение языков', 'slug' => 'language-learning'],
                        ['name_en' => 'Coaching & Mentoring', 'name_ru' => 'Коучинг и менторинг', 'slug' => 'coaching-mentoring'],
                    ],
                ],
                [
                    'name_en' => 'Other Expenses',
                    'name_ru' => 'Прочие расходы',
                    'slug'    => 'other-expenses',
                    'children' => [
                        ['name_en' => 'Other Expenses', 'name_ru' => 'Прочие расходы', 'slug' => 'other-expenses'],
                        ['name_en' => 'Fines & Penalties', 'name_ru' => 'Штрафы и пени', 'slug' => 'fines-penalties'],
                        ['name_en' => 'Uncategorized', 'name_ru' => 'Не категоризировано', 'slug' => 'uncategorized'],
                        ['name_en' => 'Lost Money', 'name_ru' => 'Потерянные деньги', 'slug' => 'lost-money'],
                        ['name_en' => 'Gambling & Lottery', 'name_ru' => 'Азартные игры и лотереи', 'slug' => 'gambling-lottery'],
                        ['name_en' => 'Tobacco & Vaping', 'name_ru' => 'Табак и вейпинг', 'slug' => 'tobacco-vaping'],
                    ],
                ],
            ]
        ];

        foreach ($categories as $type => $groups) {
            foreach ($groups as $group) {
                $parent = Category::updateOrCreate(
                    ['slug' => $group['slug']],
                    [
                        'parent_id' => null,
                        'type'      => $type,
                        'name_en'   => $group['name_en'],
                        'name_ru'   => $group['name_ru'],
                    ]
                );

                foreach ($group['children'] as $child) {
                    Category::updateOrCreate(
                        ['slug' => $child['slug']],
                        [
                            'parent_id' => $parent->id,
                            'type'      => $type,
                            'name_en'   => $child['name_en'],
                            'name_ru'   => $child['name_ru'],
                        ]
                    );
                }
            }
        }
    }
}
